[project]
name = "1deltaexchangecryptointraday"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.8.1",
    "ddgs>=9.5.5",
    "dotenv>=0.9.9",
    "openai>=1.106.1",
]
